### ISSUE TITLE
Erro ao emitir boleto - Magento 2.4.4 PHP7.4

### ISSUE THREAD

**Issue by schossler** [wirecardBrasil/magento2#102]
main.CRITICAL: Exception: Invalid JSON was returned by the gateway in /home/site/public_html/app/code/Moip/Magento2/Gateway/Http/Client/CreateOrderAuthorizeClient.php:121

No momento só tentei por boleto o teste. Alguma dica @elisei ?

**Comment by elisei** [comment]
Olá André, tudo bem?

Sugiro habilitar o log do módulo, então testar o pagamento novamente e
analisar o arquivo var/log/payment.log que será criado. Lá você irá ver
qual a resposta do Moip ao seu request.

Isto fica feliz em ser útil.


*Bruno Elisei*
*O2**ti Soluções Web*
(34) 98442-7885



Em qui., 17 de nov. de 2022 às 16:10, André Schossler <
***@***.***> escreveu:

**Comment by schossler** [comment]
obrigado pela rápida resposta Elisei, segue payment.log


[2022-11-18T11:13:12.765648+00:00] main.DEBUG: array (
  'exception' => 'Unable to unserialize value. Error: Syntax error',
  'url' => 'https://api.moip.com.br/v2/orders',
  'request' => '{"ownId":"000003270","amount":{"currency":"BRL","total":1200,"subtotals":{"shipping":0,"discount":-0,"addition":0}},"items":[{"product":"Uruguai 1 Pes$
  'response' => '<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>',
) [] []

**Comment by elisei** [comment]
Olá André,

Nesse caso precisa entrar em contato com ***@***.***,
será necessário informar o IP do servidor no chamado!

Isto fica feliz em ser útil.


*Bruno Elisei*
*O2**ti Soluções Web*
(34) 98442-7885



Em sex., 18 de nov. de 2022 às 08:19, André Schossler <
***@***.***> escreveu:

**Comment by schossler** [comment]
resolvido contatando suporte, obrigado @elisei
