### ISSUE TITLE
Instalação composer

### ISSUE THREAD

**Issue by luizgustavoagomes** [wirecardBrasil/magento2#26]
Estou tendo o seguinte erro ao tentar rodar a instalação via o composer, uso magento 2.2.5 php 7.1
![errocomposer1](https://user-images.githubusercontent.com/26871695/47536690-ffea3300-d897-11e8-94bd-d5a3bad90ec9.PNG)
![errocomposer](https://user-images.githubusercontent.com/26871695/47536692-ffea3300-d897-11e8-8fd6-669451048d00.PNG)

**Comment by elisei** [comment]
Vá ao [Magento Marketplace](https://account.magento.com/applications/customer/login/).
Depois de logar, clique em My access Keys como na figura abaixo:
![img](https://github.com/thiagolima-bm/magento2doc/raw/master/images/install_mkpl_access-keys.png)

Se você já tem as chaves, utilize a chave publica como nome de usuário e a chave privada como senha.
Para criar um novo par de de chaves, clique em Create a New Access Key.
![img](https://github.com/thiagolima-bm/magento2doc/raw/master/images/install_mkpl_access-keys-detail.png)
