### ISSUE TITLE
Erro inesperado ao ativar o sandbox

### ISSUE THREAD

**Issue by luizgustavoagomes** [wirecardBrasil/magento2#27]
Quando fui autorizar o sandbox no site do moip retornou esse erro, uso magento 2.2.5 com php 7.1
![erroativar](https://user-images.githubusercontent.com/26871695/47608010-08f51480-d9fe-11e8-8946-ddffcf438830.PNG)

**Comment by elisei** [comment]
@luizgustavoagomes 
por favor tente novamente. possivelmente foi um queda do ambiente de teste.

**Comment by Davi-Backendorf** [comment]
Boa tarde senhores, tenho um erro muito parecido. 
Ao tentar com a conta sandbox, depois de autorizar e quando sou redirecionado ao painel do Magento recebo o seguinte erro (Conforme print): 
![erro-moip-sandbox](https://user-images.githubusercontent.com/37641316/65456313-69175500-de1f-11e9-93b1-b02fe2937a23.png)
Meu ambiente:
 - PHP7.1-fpm
 - Magento OpenSource 2.3.2

**Comment by elisei** [comment]
Olá @Davi-Backendorf 

Na verdade ao que parece seu erro está relacionado ao excesso de url de preferencias cadastradas para a sua conta. 

Por favor entre em contato com suporte.br@wirecard.com e solicite a limpeza das suas atuais preferências de webhooks.

**Comment by ecommercegluk** [comment]
Bom dia, entrei em contato com o suporte que fez o procedimento e isso resolveu meu problema.
Obrigado!

**Comment by Davi-Backendorf** [comment]
Bom dia, entrei em contato com o suporte que fez o procedimento e isso resolveu meu problema.
Obrigado!
