### ISSUE TITLE
/rest/default/V1/carts/mine/payment-information:1 Failed to load resource: the server responded with a status of 400 (Bad Request)

### ISSUE THREAD

**Issue by wubuyun** [wirecardBrasil/magento2#31]
![default](https://user-images.githubusercontent.com/35350235/48589869-3f56ed00-e935-11e8-8a70-94eda5520597.jpg)

**Comment by elisei** [comment]
@wubuyun A principio não vejo relação com o nosso módulo, por favor caso tenha algum registro acrescente a esse issues.
