### ISSUE TITLE
Invalid return type

### ISSUE THREAD

**Issue by samuelmafra** [wirecardBrasil/magento2#32]
Bom dia,

Encontrei diversos erros em nossos logs, acredito estar relacionado ao update dos pedidos a serem cancelados:

{"0":"Invalid return type","1":"#0 /home/domain/public_html/magento2/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#1 /home/domain/public_html/magento2/vendor/magento/framework/App/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#2 /home/domain/public_html/magento2/pub/index.php(75): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#3 {main}","url":"/moip/notification/Cancel","script_name":"/index.php"}

Alguém mais com este erro?

Obrigado.

**Comment by elisei** [comment]
Oi @samuelmafra 
Isto é uma informação de system e não de exception, ele está apenas informando que a url não tem nenhuma saída, o que é fato pois é apenas a comunicação da entrega.
