### ISSUE TITLE
Erro ao tentar processar pedido

### ISSUE THREAD

**Issue by envolvelabs** [wirecardBrasil/magento2#33]
Olá, em alguns caso o módulo esta travando na requisição AJAX ao tentar processar o pagamento, inspecionando o console eu tenho dois erros:

Erro 500 em POST https://www.../rest/default/V1/carts/mine/payment-information

e um erro JavaScript que ao inspecionar o retorno encontrei a seguinte mensagem:

Fatal error: Uncaught TypeError: Argument 2 passed to Moip\Resource\Payment::setCreditCardHash() must be an instance of Moip\Resource\Holder, instance of Moip\Resource\Customer given, called in /.../vendor/moip/magento2/Helper/Data.php on line 411 and defined in /.../vendor/moip/moip-sdk-php/src/Resource/Payment.php:442
Stack trace:
#0 /.../vendor/moip/magento2/Helper/Data.php(411): Moip\Resource\Payment->setCreditCardHash('bmVIdkKJys9kz40...', Object(Moip\Resource\Customer))
#1 /.../vendor/moip/magento2/Model/PaymentMethodCc.php(146): Moip\Magento2\Helper\Data->addPayCcMoip(Object(Moip\Resource\Orders), Object(Moip\Resource\Customer), Object(Magento\Sales\Model\Order\Payment\Interceptor), Object(Magento\Sales\Model\Order\Payment\Interceptor))
#2 /.../vendor/magento/module-sales/Model/Order/Payment/Operations/OrderOperation.php(35): Moip\Magento2\Model\PaymentMethodCc->order in /.../vendor/moip/moip-sdk-php/src/Resource/Payment.php on line 442
{"messages":{"error":[{"code":500,"message":"Erro interno do servidor. See details in report api\/532743691689"}]}}

Alguma pista do que pode ser?

**Comment by envolvelabs** [comment]
Mais uma observação, isso começou a cerca de 5 dias atrás, após atualizarmos o módulo para sua última versão.

**Comment by elisei** [comment]
Olá @envolvelabs 

Consegue me enviar uma url em que consiga reproduzir esse erro?

**Comment by envolvelabs** [comment]
Olá @elisei , segue em ambiente de homologação com Moip em modo sandbox: https://homologacao.truefriends.com.br.
Fazendo novos testes com um módulo de debug eu capturei o seguinte erro: Magento\Framework\Exception\LocalizedException: Payment failed Notice: Undefined offset: 3 in /srv/www/htdocs/homologacao.truefriends.com.br/vendor/moip/magento2/Helper/Data.php on line 157 in /srv/www/htdocs/homologacao.truefriends.com.br/vendor/moip/magento2/Model/PaymentMethodCc.php:167

**Comment by elisei** [comment]
@envolvelabs 
Por favor veja esse outro issues -> https://github.com/wirecardBrasil/magento2/issues/16#issuecomment-405659853 acho que se aplica a vocês.

**Comment by envolvelabs** [comment]
Eu resolvi o problema do mapeamento, mas agora recebo esse retorno do endpoint do pagamento:

Fatal error: Uncaught TypeError: Argument 2 passed to Moip\Resource\Payment::setCreditCardHash() must be an instance of Moip\Resource\Holder, instance of Moip\Resource\Customer given, called in /srv/www/htdocs/truefriends.com.br/vendor/moip/magento2/Helper/Data.php on line 396 and defined in /srv/www/htdocs/truefriends.com.br/vendor/moip/moip-sdk-php/src/Resource/Payment.php:442
Stack trace:
#0 /srv/www/htdocs/truefriends.com.br/vendor/moip/magento2/Helper/Data.php(396): Moip\Resource\Payment->setCreditCardHash('RyeMaVmNfNHARib...', Object(Moip\Resource\Customer))
#1 /srv/www/htdocs/truefriends.com.br/vendor/moip/magento2/Model/PaymentMethodCc.php(146): Moip\Magento2\Helper\Data->addPayCcMoip(Object(Moip\Resource\Orders), Object(Moip\Resource\Customer), Object(Magento\Sales\Model\Order\Payment\Interceptor), Object(Magento\Sales\Model\Order\Payment\Interceptor))
#2 /srv/www/htdocs/truefriends.com.br/vendor/magento/module-sales/Model/Order/Payment/Operations/OrderOperation.php(35): Moip\Magento2\Model\PaymentMethodCc->order in /srv/www/htdocs/truefriends.com.br/vendor/moip/moip-sdk-php/src/Resource/Payment.php on line 442
{"messages":{"error":[{"code":500,"message":"Erro interno do servidor. See details in report api\/375304763625"}]}}
