### ISSUE TITLE
Erro ao tentar efetuar pagamento

### ISSUE THREAD

**Issue by envolvelabs** [wirecardBrasil/magento2#34]
Esta dando esse erro ao tentar fazer um pagamento:

POST https://www.truefriends.com.br/rest/default/V1/carts/mine/payment-informatio

Fatal error: Uncaught TypeError: Argument 2 passed to Moip\Resource\Payment::setCreditCardHash() must be an instance of Moip\Resource\Holder, instance of Moip\Resource\Customer given, called in /srv/www/htdocs/truefriends.com.br/vendor/moip/magento2/Helper/Data.php on line 396 and defined in /srv/www/htdocs/truefriends.com.br/vendor/moip/moip-sdk-php/src/Resource/Payment.php:442
Stack trace:
#0 /srv/www/htdocs/truefriends.com.br/vendor/moip/magento2/Helper/Data.php(396): Moip\Resource\Payment->setCreditCardHash('RyeMaVmNfNHARib...', Object(Moip\Resource\Customer))
#1 /srv/www/htdocs/truefriends.com.br/vendor/moip/magento2/Model/PaymentMethodCc.php(146): Moip\Magento2\Helper\Data->addPayCcMoip(Object(Moip\Resource\Orders), Object(Moip\Resource\Customer), Object(Magento\Sales\Model\Order\Payment\Interceptor), Object(Magento\Sales\Model\Order\Payment\Interceptor))
#2 /srv/www/htdocs/truefriends.com.br/vendor/magento/module-sales/Model/Order/Payment/Operations/OrderOperation.php(35): Moip\Magento2\Model\PaymentMethodCc->order in /srv/www/htdocs/truefriends.com.br/vendor/moip/moip-sdk-php/src/Resource/Payment.php on line 442
{"messages":{"error":[{"code":500,"message":"Erro interno do servidor. See details in report api\/375304763625"}]}}

**Comment by elisei** [comment]
Olá @envolvelabs,

Por favor atualize o módulo.
