### ISSUE TITLE
Split de pagamentos

### ISSUE THREAD

**Issue by raphaelhagi** [wirecardBrasil/magento2#36]
Boa tarde,

Lendo a breve documentação, não encontrei informações sobre este plugin para o Magento suportar split de pagamentos, conforme documentação em https://dev.wirecard.com.br/docs/split-de-pagamento

Existe alguma previsão em roadmap para a funcionalidade ser contemplada?

**Comment by elisei** [comment]
Olá @raphaelhagi 

Nosso módulo segue o modelo de desenvolvimento da Magento que "não tem suporte a split" ou seja não haverá no módulo um suporte ao recurso que a plataforma não possuí. 

Mas para consumir nossos recursos de marketplace da API, você precisa personalizar o módulo localmente para a regra de seu negócio e módulos que usou para ter esse recurso em seu Magento.

**Comment by raphaelhagi** [comment]
@elisei obrigado pela rápida resposta ao meu questionamento.
