### ISSUE TITLE
Endereco nao contem mais que 1 linha(s)

### ISSUE THREAD

**Issue by Jackcar** [wirecardBrasil/magento2#37]
Ola,

Atualizei a biblioteca e apos tentar efetuar uma compra utilizando Cartao de Credito ou Boleto, recebi a seguinte mensagem:

"Endere\u00e7o\" n\u00e3o contem mais que 1 linha(s)."

Abaixo esta o json que esta sendo enviado.

{  
   "cartId":"24",
   "billingAddress":{  
      "customerAddressId":"9",
      "countryId":"BR",
      "regionId":"508",
      "regionCode":"SP",
      "region":"São Paulo",
      "customerId":"7",
      "street":[  
         "Av. Voluntário Fernando Pinheiro Franco",
         "127",
         "Centro",
         "Casa"
      ],
      "company":"Nenhuma",
      "telephone":"999182899",
      "postcode":"08710500",
      "city":"Mogi das Cruzes",
      "firstname":"Rodrigo",
      "lastname":"Vilaca",
      "vatId":"05859125981",
      "saveInAddressBook":null
   },
   "paymentMethod":{  
      "method":"moipcc",
      "additional_data":{  
         "cc_number":"4012001037141112",
         "cc_type":"visa",
         "cc_exp_month":"12",
         "cc_exp_year":"2022",
         "fullname":"Ro",
         "installments":"1",
         "hash":"jC+nSr13ghTQRk8BQeMINAm1qkd6noiSaTGCyae/WvNuVXBK58hBRugc7b0IffxOiBjNUyaZ33LvgJsGP4wIz4SMVO3Q8MmTAJd1VC54dIeVMYGBBYCTBxGZaSzdgIasD2u8sMn+NBE21BE+wVz1hSYA4sbtOvB6Pk4nlQU596k0WgSV5pULV2MxYZv99+d9hy2dZzyXWFQlg49M8OWRrSmYoKsyek1gU8Ttw8ZBVTGETNoPGF3VU8m0/9r0I/b6I/CAP0LdKoIOXG0DU/Hj037hRzdie48iOpTOUBWCWxM4+JufMrex/jpjWIhqBfCsrkFM9WqHoV6OcUSdvuBC4g=="
      }
   }
}

Alguem sabe o que poderia ser?

Obrigado.

**Comment by Jackcar** [comment]
Ola @elisei,

A biblioteca foi atualizada juntamente com o modulo do moip.

**Comment by Jackcar** [comment]
Consegui ajustar isso, de algum jeito, as linhas de endereco haviam mudado, porem agora estou recebendo a seguinte mensagem:
"Ocorreu um erro no servidor. Por favor, tente fazer o pedido novamente."

Ao tentar pagamento com boleto, ocorre o seguinte erro:
"Notice: Undefined property: stdClass::$payBoleto in \vendor\moip\moip-sdk-php\src\Resource\Payment.php on line 278"

Estou tentando realizar multipedidos e multipagamentos.

Obrigado

**Comment by elisei** [comment]
Oi @Jackcar 

Esse erro é da sdk-php que usamos:
https://github.com/wirecardBrasil/moip-sdk-php/blob/master/src/Resource/Payment.php#L278
Nessa versão do nosso módulo subimos a versão da sdk que usamos possivelmente isto gerou conflitos com a sua logica para mktplace, você pode remover temporariamente ela ver se assim consegue fazer o pagamento corretamente?
