### ISSUE TITLE
Compilação Magento 2.2.6

### ISSUE THREAD

**Issue by gerbesf** [wirecardBrasil/magento2#39]
Sabem se está com suporte para o Magento 2.2.6 ?

Estou recebendo este erro ao fazer a compilação
bin/magento setup:di:compile
  [RuntimeException]                                                                                                                                                                                              
  Class Moip\Auth\Connect does not exist                                                                                                                                                                          
  Class Moip\Magento2\Controller\Adminhtml\System\Config\Oauth\Interceptor generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- af  
  ter running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class   
  object to the signature of the related construct method, only. 

No log fala sobre permissão na pasta, mas não é exatamente isto, pois mesmo dando as permissões continua na mesma mensagem.

**Comment by elisei** [comment]
Olá @gerbesf 

Sim é compátivel até a versão 2.3.0 (a última lançada oficialmente).

**Comment by gerbesf** [comment]
Consegui instalando via composer.
