### ISSUE TITLE
Dúvida - Webhooks

### ISSUE THREAD

**Issue by gerbesf** [wirecardBrasil/magento2#41]
Fiz um teste em ambiente de produção, e o pagamento foi aprovado.
porem na loja o status não foi alterado nem a fatura criada, é necessário alguma configuração para o retorno/notificações ?!?!

Webhooks no painel
EVE-*** | PAY-*** | PAYMENT.AUTHORIZED | http:// *** /moip/notification/Capture | FAILED | 2019-02-11T17:15:12.580Z

Será que o Varnish está bloqueando a rota?

----------------
Ao clicar nestes botões Accept ou Deny ele deveria consultar na api ??

![image](https://user-images.githubusercontent.com/12032611/52588112-e0fdb580-2e22-11e9-849a-5d07edecbf8f.png)

**Comment by elisei** [comment]
Olá @gerbesf 

Verifique se o seu domínio está disponível para acesso externo, além disso veja se a url está correta (com https se houver), caso não esteja desconecte o app e faça nova autorização.

**Comment by gerbesf** [comment]
No ambiente Sandbox estou recebendo 500. mas não consigo detectar o erro.

Estou recebendo 500 no http
54.165.108.234 - - [11/Feb/2019:17:04:23 -0500] "POST /moip/notification/Cancel HTTP/1.1" 500 5044 "-" "Go-http-client/1.1"

no log do magento
==> var/log/system.log <==
[2019-02-11 22:04:30] main.ERROR: Payment not update Authentication Credentials Invalid
