### ISSUE TITLE
phpunit/phpunit-mock-objects is abandoned,

### ISSUE THREAD

**Issue by delcain** [wirecardBrasil/magento2#42]
Recebo a seguinte mensagem de erro ao tentar instalar via composer no Magento 2.2 by Bitnami

Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.

**Comment by elisei** [comment]
Olá @delcain, 

Não há nenhuma dependência nossa para esse pacote, possivelmente é algum outro módulo já instalado que está desatualizado.
