### ISSUE TITLE
"The payment disallows storing objects." ao tentar finalizar um pagamento

### ISSUE THREAD

**Issue by blopa** [wirecardBrasil/magento2#44]
Bom dia.

Estou recebendo o erro "The payment disallows storing objects." ao tentar realizar um pagamento via Cartao de Credito transparente.

Versao do Modulo: 1.0.16
Versao do Magento: 2.2.7

Aparentemente o erro eh disparado na funcao `setAdditionalInformation` do modulo Magento Payment.

**Comment by blopa** [comment]
Uhmn parece que o problema ta relacionado para quando voce habilita o checkout agreement

**Comment by blopa** [comment]
Criei o PR #45 que resolveu o problema pra mim, nao sei se eh uma solucao permanente, mas eh como esta no modulo Express do PayPal no branch 2.3 do Magento2.

**Comment by elisei** [comment]
PR aceito, obrigado pela colaboração!
