### ISSUE TITLE
Vendas travadas em Payment Review

### ISSUE THREAD

**Issue by murilopereirame** [wirecardBrasil/magento2#48]
**Pré condições**

1. Magento 2.3.1
2. Moip/Magento2 - Última versão no composer

**Passos para reproduzir**

- Adicionar produtos no carrinho
- Prosseguir para checkout
- Selecionar alguma forma de pagamento MOIP (CC ou boleto)
- Realizar pedido

**Resultado esperado**

- Pedido ser realizado
- Status do pedido como "Processing"
- Liberação para enviar

**Resultado atual**
Quando a compra é realizada pro cartão de crédito, o status fica em _Payment Review_ e não sai disso, de tal forma que eu não consigo adicionar envio para o pedido. Quando eu teno aprovar o pagamento na página do pedido, recebo a mensagem _Não há necessidade de aprovar este pagamento._, já com boleto, o status fica como _Processing_, porém, continuo sem conseguir enviar e aceitar o pagamento.

**Comment by elisei** [comment]
Olá Murilo, 

Essas são as principais causas de erro no retorno de status:

- Módulo desatualizado
- SSL inválido, você pode verificar a validade de seu ssl aqui: https://www.sslshopper.com/ssl-checker.html
- Domínio com acesso restrito. Acesso mediante senhas ou autenticações do tipo basic, configuração de dns locais...
- Alterações no domínio após autorização do módulo (uso de https, virada de um domínio temporário para o domínio final)
- Chave de acesso do Webhooks Inválida.

Para o caso 1, atualize usando o composer. 
Para os casos 2 e 3, não há o que possamos fazer, requer ajuste do lado do servidor.
Para os casos 3 e 4, basta desconectar a autorização atual do módulo e refaze-la.

**Comment by murilopereirame** [comment]
O servidor ainda não conta com SSL ainda, então é possível concluir a compra, porém não vou receber respostas do Gateway?

**Comment by elisei** [comment]
Oi Murilo, 

Não ssl inválido é diferente de ausente... se está ausente não é um problema, analise os outros pontos.

No entanto é importante confirmar se a versão que está usando é de fato a mais recente: 1.0.21

**Comment by murilopereirame** [comment]
A versão instalada, de acordo com o composer.json, é a ^1.0, isto está correto?

**Comment by elisei** [comment]
Olá @murilopereirame 

Como pode ver aqui https://github.com/wirecardBrasil/magento2/blob/master/composer.json#L11 é apontado para a versão maior ou igual a 2.3.0

**Comment by Jackcar** [comment]
@murilopereirame você conseguiu alguma coisa? 

Estou com o mesmo problema, tenho a versão 2.3.0 do Magento e ultima versão do moip 1.0.22, porém os pedidos não saem do status "Aguardando pagamento". 

Estou utilizando o sandbox.

Alguma dica?

**Comment by elisei** [comment]
@Jackcar 

Eu sei que você já roda alguns projetos conosco então acredito que o seu problema seja outro:
Nossa API limitou o uso de preferências para até 5 urls.... 

Como está em sandbox, a solução mais simples é criar uma nova conta em:
https://bem-vindo-sandbox.wirecard.com.br (você pode falsear os dados ai usando um gerador de cpf)...

Fora isso o magento em suas versões mais recentes aplica uma validação do Csr, isso é feio por uma nova "lib" que é alçada por updates da versão, se for o caso de estar com um projeto abaixo da versão 2.3 me avise que te passo o que precisa ser feito.

**Comment by Jackcar** [comment]
@elisei

Eu estava desenvolvendo localmente e agora estou realizando o deploy em produçao, testei em algumas hospedagens, mas nunca saiu deste estado.

Vou tentar criar uma nova conta no sandbox para verificar. 

Estou usando a versao 2.3 do magento mesmo.

Obrigado

**Comment by 4devs-net-br** [comment]
https://4devs.net.br/gerador-cpf
