### ISSUE TITLE
Magento 2.3.1 - PHP Fatal error:  Uncaught Error: Call to a member function getLastTransId()

### ISSUE THREAD

**Issue by gcampedelli** [wirecardBrasil/magento2#49]
Sempre que o Wirecard/Moip envia notificações o site cai. 

FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getLastTransId() on null in /var/www/html/magento2/vendor/moip/magento2/Controller/Notification/Capture.php:76
Stack trace:
#0 /var/www/html/magento2/generated/code/Moip/Magento2/Controller/Notification/Capture/Interceptor.php(50): Moip\Magento2\Controller\Notification\Capture->execute()
#1 /var/www/html/magento2/vendor/magento/framework/App/Action/Action.php(108): Moip\Magento2\Controller\Notification\Capture\Interceptor->execute()
#2 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Moip\Magento2\Controller\Notification\Capture\Interceptor->___callParent('dispatch', Array)
#4 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Moip\Magento2\Controller\Notification\Capture\Interceptor->Magento\Fram" while reading response header from upstream, client: 127.0.0.1, server: myhost.com.br, request: "POST /moip/notification/Capture HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:",

**Comment by elisei** [comment]
@gcampedelli 

Possivelmente não foi gerada a transação para esse pedido, verifique na conta Wirecard e realização o update manualmente para esse pedido (caso ele exista na wirecard).
