### ISSUE TITLE
Repetindo valor no checkout

### ISSUE THREAD

**Issue by 41154135** [wirecardBrasil/magento2#50]
Durante o checkout, o valor da forma de pagamento "Cartão de crédito" está sendo exibido duas vezes. Achei que era problema no frontend, mas a resposta esta vindo duplicada no JSON das formas de pagamento

https://i.imgur.com/ascbkFC.png

**Comment by elisei** [comment]
@41154135 

Nosso módulo não faz o request do payment method, isso é uma função do checkout e não nossa.
