### ISSUE TITLE
Fatal error:  Uncaught Error: Class 'Moip\Magento2\Helper\LocalizedException'

### ISSUE THREAD

**Issue by roneclay** [wirecardBrasil/magento2#53]
Tentei fazer Pull Request com essa alteração, mas não tenho permissões ou sei lá o quê.
De qualquer modo, sempre que instalamos o módulo e iniciamos testes de vendas passamos pelo mesmo problema e precisamos resolver na /vendor para prosseguir.

O erro acontece em /var/www/vendor/moip/magento2/Helper/Data.php:227

Resolvemos sempre adicionando, logo abaixo do namespace:
**use Magento\Framework\Exception\LocalizedException;**

Nas próximas atualizações teremos essa correção?

**Comment by elisei** [comment]
Oi @roneclay 

Obrigada pela contribuição será disponível na próxima versão! ;)
