### ISSUE TITLE
Não funciona com backorder 

### ISSUE THREAD

**Issue by ludioao** [wirecardBrasil/magento2#54]
Não estou conseguindo gerar pedido com produtos sob encomenda. 

Será que tem alguma regra na API do MoIP que esteja fazendo este bloqueio?

**Comment by elisei** [comment]
Olá @ludioao,

Vendas via admin ainda não está presente no módulo. Esse recurso estará disponível em futuras versões.

**Comment by ludioao** [comment]
@elisei não é sobre isso, quanto ao vendas via admin já estava ciente. 

estou dizendo quanto a produtos que já estão fora de estoque, mas ainda assim o cliente pode fazer encomendas. 

na hora de fazer o checkout, o moip está retornando erro por causa dessa regra (que é nativa do magento).

**Comment by elisei** [comment]
Olá @ludioao 

Por favor descreva passos e condições para reprodução do issues:
-

-  Versão usada
  Módulo e a do Magento
 - Configuração aplicado 
   Módulo ao Magento
