### ISSUE TITLE
Erro: /vendor/moip/magento2/Helper/Data.php on line 203

### ISSUE THREAD

**Issue by periclesbezerra** [wirecardBrasil/magento2#55]
Erro de na criação do cliente Notice: Undefined variable: _typedocument in /chroot/home/a8c3fb93/vivoci.com.br/vendor/moip/magento2/Helper/Data.php on line 203

**Comment by elisei** [comment]
Olá @periclesbezerra, 

Você está recebendo a informação que a variável não foi definida, a definição dela deverá ser feita em:
https://github.com/wirecardBrasil/magento2/wiki/Relacionamento-de-Atributos
