### ISSUE TITLE
Erro no 'throw' da mensagem 'Documento fiscal inválido, CPF ou CNPJ não preenchido.'

### ISSUE THREAD

**Issue by robsoned** [wirecardBrasil/magento2#60]
Em helper/Data.php o seguinte código deveria printar o erro `Documento fiscal inválido, CPF ou CNPJ não preenchido.`

		try{
			if($taxvat != ""){
				$customer = $customer->create();
			}
		} catch(\Exception $e) {
			throw new LocalizedException(__( "Documento fiscal inválido, CPF ou CNPJ não preenchido."));
			return $this;
		}

Porém está faltando `use Magento\Framework\Exception\LocalizedException;` no início do arquivo.

Resultando no seguinte erro: Na página de checkout, ou é redirecionado para o carrinho de volta, ou um erro 'vazio' aparece na tela. E no log de api report o seguinte erro aparece:

`"Fatal Error: 'Uncaught Error: Class 'Moip\\Magento2\\Helper\\LocalizedException' not found`.

**Comment by elisei** [comment]
@robsoned 

Há uma nova versão que corrige esse problema.

**Comment by awakebrasil** [comment]
Estou recebendo o mesmo erro tanto no cartão quanto no boleto usando o  modulo mais atualizado, mesmo usando o CPF solicitado junto com o cartão de credito gera erro, Checkout como visitante. 

Mesmo ativando o vat_id ele fala que não tem CPF preenchido, alguma ideia?

**Comment by elisei** [comment]
@awakebrasil 

Problema que relata não é relacionado ao esse issues. Aqui é problema reportado é que não havia "LocalizedException" que lançava qual era o erro pagamento.

O problema descreve está relacionado ao #16 ele fica permanentemente aberto como guia para solução do problema.
