### ISSUE TITLE
Request does not match any route

### ISSUE THREAD

**Issue by Jackcar** [wirecardBrasil/magento2#62]
Ola, 

Estou tentando obter informações de pagamento de um pedido no ADMIN do Magento 2 e ao clicar no botão "Obter informações de pagamento" ocorre o seguinte erro:
`request does not match any route` 

Alguém sabe o que poderia ser? 

Obrigado.

**Comment by elisei** [comment]
Olá @Jackcar 

É apenas para um pedido ou com todos?

**Comment by Jackcar** [comment]
Olá @elisei,

Desculpa, erro meu. 

Era um observer que estava travando o processo da atualização do pagamento.

Obrigado.
