### ISSUE TITLE
Erro Pagamento Data.php

### ISSUE THREAD

**Issue by awakebrasil** [wirecardBrasil/magento2#64]
Bom dia pessoal estou recebendo o seguinte erro na finalização do pedido, 

Erro de criação do cliente Notice: Undefined Offset: 3 in XXXXX/vendor/moip/magento2/Helper/Data.php on line 133

Alguém com o mesmo problema...

**Comment by elisei** [comment]
Olá @awakebrasil 

A linha aponta para o relacionamento do seu atributo de endereço (bairro) com a nossa API.

Reveja o seu [relacionamento de atributos](https://github.com/wirecardBrasil/magento2/wiki/Relacionamento-de-Atributos) apontando onde é capturada em sua estrutura de endereço.
