### ISSUE TITLE
Erro ao fazer a encomenda

### ISSUE THREAD

**Issue by NatanCervinski** [wirecardBrasil/magento2#66]
Magento-2.3.4
Quando clico em Place Order, aparece esse erro no pagamento em boleto
![Captura de tela de 2020-02-21 17-18-58](https://user-images.githubusercontent.com/53199974/75068655-5be5bb80-54ce-11ea-9482-cfe756f12586.png)
Com cartão de cŕédito simplesmete acontece nada
![Captura de tela de 2020-02-21 17-25-25](https://user-images.githubusercontent.com/53199974/75069060-2d1c1500-54cf-11ea-9da2-c4af500899a7.png)

**Comment by elisei** [comment]
Olá @NatanCervinski ,

Ao que parece o relacionamento de atributos não foi realizado corretamente por favor veja as orientações em nossa Wiki:
https://github.com/wirecardBrasil/magento2/wiki/Relacionamento-de-Atributos

**Comment by NatanCervinski** [comment]
Conferi o relacionamento e aparenta estar tudo correto
![Captura de tela de 2020-02-24 09-25-43](https://user-images.githubusercontent.com/53199974/75152428-c02f9780-56e7-11ea-9688-ceffeec96c01.png)

**Comment by elisei** [comment]
Oi @NatanCervinski 

Os dados requeridos precisam ser válidos, o CEP tem que ser o da UF que informa, o telefone deverá ter ddd válidos. o número do seu endereço precisa ser um número...

**Comment by NatanCervinski** [comment]
Provavelmente havia um erro no cpf, coloquei para pegar do cadastro do usuário, e o erro mudou (estou usando dados válidos, apeans escondi o telefone)
![Captura de tela de 2020-02-24 10-16-54](https://user-images.githubusercontent.com/53199974/75155521-05a39300-56ef-11ea-9413-cf407335f34f.png)
