### ISSUE TITLE
Pedido é confirmado mesmo se cartão for inválido

### ISSUE THREAD

**Issue by Jackcar** [wirecardBrasil/magento2#67]
Olá,

Estou com um problema, alguns clientes efetuaram uma compra com cartão inválido, um de débito e outro com dados incorretos do cartão, porém ao fechar a compra, o pedido é concluído com sucesso e apenas após o pedido é cancelado.

Tem alguma maneira de evitar isso e não direcionar para a tela de sucesso até que o cartão seja aprovado e pago?

Obrigado.

**Comment by elisei** [comment]
Oi @Jackcar 

Quando é uma compra no cartão o módulo não irá obter o status de imediato mesmo, e tem vários motivos aqui para isso, destaco que iria ser um pouco confuso ter n pedidos na wirecard que não existem no magento...

Uma opção que requer desenvolvimento é usar uma [pré-autorização](https://github.com/wirecardBrasil/moip-sdk-php/wiki/Criar-um-pagamento#cart%C3%A3o-de-cr%C3%A9dito) durante o processo de pagamento, mas depois de "pré-aprovado" você teria que fazer a [captura do pedido](https://github.com/wirecardBrasil/moip-sdk-php/wiki/Capturar-um-pagamento-pr%C3%A9-autorizado)

**Comment by Jackcar** [comment]
Oi @elisei,

Entendi. Esta pré-autorização já verificaria se os dados do cartão estão corretos, correto?

**Comment by elisei** [comment]
Olá @Jackcar 

Sim
