### ISSUE TITLE
Valor incorreto

### ISSUE THREAD

**Issue by Jackcar** [wirecardBrasil/magento2#68]
Olá @elisei,

Estou com um problema, os clientes estão recebendo um valor incorreto no email de confirmação do pedido, um valor exorbitante igual a imagem abaixo.

<img width="562" alt="Captura de Tela 2020-05-27 às 20 33 50" src="https://user-images.githubusercontent.com/7013608/83064981-9b3a2000-a05a-11ea-97d1-2adc1cdfe670.png">

Você saberia o que pode ser? 

Obrigado.

**Comment by elisei** [comment]
@Jackcar 

"MOR" é uma referencia a multiorder, nosso módulo não usa multiorder, você está usando nosso módulo oficial?

**Comment by Jackcar** [comment]
Estou usando o módulo oficial, porém fiz algumas modificações para suportar multiorder, tentei seguir o existente para uma order normal.

**Comment by elisei** [comment]
@Jackcar 

Entendi, no cenário comum como o módulo sem alterações, você também encontra esse erro?

**Comment by Jackcar** [comment]
@elisei 

Acredito que não, deve ter sido alguma coisa que alterei, estou investigando para saber o que pode ser. Você teria alguma pista?

**Comment by Jackcar** [comment]
@elisei 

Acabei de testar aqui com o módulo sem alterações e ocorre o mesmo problema.

**Comment by elisei** [comment]
@Jackcar 

Você consegue me indicar como reproduzir esse erro usando o módulo padrão como base?

Esse módulo já vai para quase 3 anos e nunca me deparei com esse cenário, se puder me descrever qual tipo de produto usou e tem que tenha dado esse erro ou qualquer coisa que me permita reproduzir.

**Comment by Jackcar** [comment]
@elisei 

Encontrei o erro, não havia nada a ver com o módulo da Wirecard, foi alguma outra alteração que fiz que resultou nisso.

Muito obrigado pela ajuda.
