### ISSUE TITLE
Erro na processar o pagamento

### ISSUE THREAD

**Issue by nataliabmodesto** [wirecardBrasil/magento2#69]
Oi, pessoal!

Em ambiente de sandbox, ao tentar passar a compra com boleto recebo o erro: Erro na processar o pagamento.

E no console recebo os erros: 

Failed to load resource: the server responded with a status of 400 (Bad Request) payment-information:1 

POST http://lojalatika.mage2.suportemagento.com.br/rest/default/V1/carts/mine/payment-information 400 (Bad Request) jquery.js:10260 

Com cartão a compra passa normal. Sabem o que pode ser?

Obrigada!

**Comment by elisei** [comment]
Oi @nataliabmodesto 

Você chegou a analisar os logs para obter detalhes do motivo?

**Comment by elisei** [comment]
@nataliabmodesto 

Estou fechando o issue mas caso tenha algum erro por favor reabra!
