### ISSUE TITLE
Boleto com endereço de envio e não de cobrança

### ISSUE THREAD

**Issue by lima195** [wirecardBrasil/magento2#70]
Magento Version: 2.3.5-p1
PHP Version: 7.2

Problema:
No boleto não está vindo com o endereço de cobrança e sim com o de envio.

Passos para reproduzir:
1 - Crie 2 endereços diferentes de envio e cobrança
3 - Adicione um produto no carrinho e vá até o checkout
4 - Escolha o primeiro endereço como envio
5 - Escolha o segundo endereço como cobrança
6 - Escolha a opção de boleto
7 - Quando o boleto for gerado, clique em "Imprimir Boleto"
8 - Em "Sacado" vai ver o endereço de entrega e não o de cobrança

Comportamento esperado:
Ao imprimir um boleto, em "Sacado" deveria vir o endereço de cobrança.

**Comment by elisei** [comment]
@lima195 

Os 2 endereços são enviados a Wirecard no entanto nossa SDK-PHP lida apenas com o de envio (para pagamentos por boleto). Infelizmente não temos como alterar esse fluxo nesse momento.

**Comment by elisei** [comment]
@lima195  

Segue o [issue](https://github.com/wirecardBrasil/moip-sdk-php/issues/278) relacionado da nossa SDK,

Em breve deixaremos de usa-la, mas por hora realmente não tem como obter o endereço de cobrança no método de pagamento por boleto.
