### ISSUE TITLE
Problema ao finalizar compra via boleto pela api rest

### ISSUE THREAD

**Issue by lima195** [wirecardBrasil/magento2#71]
Problema:
(Magento versão 2.3.5-p1)
Ao tentar finalizar a compra pela api do magento seguindo os passos:
https://devdocs.magento.com/guides/v2.4/rest/tutorials/inventory/create-order.html
E selecionando o payment method: moipboleto
A compra não é finalizada e uma mensagem de que a compra não foi finalizada, sem o real erro.

Acontece que no arquivo:
vendor/moip/magento2/Model/PaymentMethodBoleto.php na função order() na linha em que é atribuido os items do quote para uma variável, acaba vindo vazio e não é criado a order sem os items.

Solução:
trocar:
$items                             = $this->_cart->getQuote()->getAllItems();
por:
$items 				= $order->getAllItems();

ai precisa só alterar no helper para pegar a quantidade do produto de getQty por getQtyOrdered na função addProductItemsMoip() do helper data, e é possível remover a instância do cart dessa classe Model/PaymentMethodBoleto

Posso criar um pr

**Comment by elisei** [comment]
@lima195 

Obrigado pelo report e pull, será aprovado em breve!
