### ISSUE TITLE
Fatura duplicada com valor zero

### ISSUE THREAD

**Issue by samuelmafra** [wirecardBrasil/magento2#73]
Magento 2.3.4.

Capturado o valor de R$ 0,00 online.

Depois da captura manual pela Magento, em algumas ocasiões o módulo cria outra fatura dentro do pedido com valor zero e sem nenhum produto, porém atualizando o valor "Total pago" do pedido + o valor da transação.

**Comment by elisei** [comment]
Samuel,

Você pode me informar a versão do módulo por favor?

**Comment by samuelmafra** [comment]
Elisei,

3.1.0

**Comment by elisei** [comment]
Oi Samuel,

Rode composer show moip/magento2 e indique o retorno por favor

**Comment by samuelmafra** [comment]
Elisei,

name     : moip/magento2
descrip. : MOIP Magento2 Extension for Magento 2 By Moip
keywords : 
versions : * 1.0.34
type     : magento2-module
license  : proprietary
source   : [git] https://github.com/wirecardBrasil/magento2.git 8dbb61b7adfb89bb62790cb1f1a4834773b97c5f
dist     : [zip] https://api.github.com/repos/wirecardBrasil/magento2/zipball/8dbb61b7adfb89bb62790cb1f1a4834773b97c5f 8dbb61b7adfb89bb62790cb1f1a4834773b97c5f

**Comment by elisei** [comment]
Oi @samuelmafra 

Acredito que o atendimento seguiu por email, por isso estou fechando! :) 

Qualquer coisa reabra aqui! ;)
