### ISSUE TITLE
Tradução pr_BR - Expiração cartão de Crédito

### ISSUE THREAD

**Issue by psincero** [wirecardBrasil/magento2#75]
Campos de mês de expiração e ano de expiração não estão sendo traduzidos para o idioma pt_BR

![image](https://user-images.githubusercontent.com/23522622/91056276-285e2800-e5fc-11ea-9413-ae573ba22adf.png)

**Comment by elisei** [comment]
Oi @psincero 

A tradução do magento irá cuidar desse termo para você, você chegou a implementar?
