### ISSUE TITLE
Como fazer o campo taxvat obrigatório no endereço de entrega?

### ISSUE THREAD

**Issue by smarley2** [wirecardBrasil/magento2#76]
Bom dia, instalei a versão 2.4 e estou tentando fazer funcionar com este módulo.
Porém o campo do CPF/CNPJ (taxvat) não é required no formulário do endereço de entrega.
O campo vat_id está como obrigatório na hora de realizar o cadastro.
Alguém tem uma sugestão de como fazer?
Na hora de finalizar o boleto da erro se não informar o taxvat no endereço de entrega.

Obrigado.

**Comment by smarley2** [comment]
Fiz mais uns testes e o resultado foi bem estranho.
Cadastrei um endereço com o CPF e outro sem o CPF na conta do usuário.
Ambos deram erro na hora de finalizar.
Só deu certo quando criei um endereço novo na página do frete, com o CPF preenchido, e dai prossegui com este endereço.
Alguém já passou por isto?

Eu tentei mudar a opção nas configurações também e o resultado foi o mesmo. "The CPF will be an attribute obtained from the"
Estou com a última versão do módulo e o Magento 2.4.0

**Comment by smarley2** [comment]
Segue saída do composer show moip/magento2

name     : moip/magento2
descrip. : MOIP Magento2 Extension for Magento 2 By Moip
keywords : 
versions : * 1.0.34
type     : magento2-module
license  : proprietary
homepage : 
source   : [git] https://github.com/wirecardBrasil/magento2.git 8dbb61b7adfb89bb62790cb1f1a4834773b97c5f
dist     : [zip] https://api.github.com/repos/wirecardBrasil/magento2/zipball/8dbb61b7adfb89bb62790cb1f1a4834773b97c5f 8dbb61b7adfb89bb62790cb1f1a4834773b97c5f
path     : /home/500010.cloudwaysapps.com/qvhrneffxe/public_html/vendor/moip/magento2
names    : moip/magento2

support
issues : https://github.com/wirecardBrasil/magento2/issues
source : https://github.com/wirecardBrasil/magento2/tree/1.0.34

autoload
files
psr-4
Moip\Magento2\ => .

requires
magento/product-community-edition >=2.3.0
moip/moip-sdk-php v3.1.0
php >=7.0

**Comment by elisei** [comment]
Olá @smarley2, tudo bem?

Esse módulo tem como premissa ser apenas um método de pagamento sem atuar em momento algum em seu cadastro de usuário, ele permite que configure qualquer atributo de seu cadastro/ou de endereço para ser enviado a nossa API.

Caso trabalhe com o um tema derivado da luma ou blank, recomendo utilizar esse módulo para atuar no fluxo de finalização -> https://github.com/elisei/full-checkout ele já oferece além da obrigatoriedade do campo vat_id diversas outras melhorias para finalização de seu pedido.
