### ISSUE TITLE
Erro Uncaught SyntaxError e Invalid JSON was returned

### ISSUE THREAD

**Issue by DevSkillsIT** [wirecardBrasil/magento2#77]
Olá Elisei,

Atualmente estamos realizando os testes no Gateway Wirecard, mas estamos com alguns problemas e espero que possa me ajudar.
A versão que utilizamos do **Magento é a 2.4.1.**

**1 - Estou um erro na linha 275 do arquivo moip_magento2_cc.js** 
No console do navegador recebo a mensagem: "Uncaught SyntaxError: missing ) after argument list" e devido ao erro não é carregada a forma de pagamento Cartão de Crédito.

**2 - Ao selecionar e tentar um pagamento através do boleto recebo a mensagem de erro no retorno do Json.** 

[2020-12-14 20:01:11] main.CRITICAL: Invalid JSON was returned by the gateway {"exception":"[object] (Exception(code: 0): Invalid JSON was returned by the gateway at /home/magentouser/public_html/app/code/Moip/Magento2/Gateway/Http/Client/CreateOrderAuthorizeClient.php:120)"} []

No debug recebo a mensagem:
[2020-12-14 19:55:21] main.DEBUG: array (
  'url' => 'https://sandbox.moip.com.br/v2/orders',
  'request' => '{"ownId":"000000136","amount":{"currency":"BRL","total":86479.86,"subtotals":{"shipping":2823,"discount":8120.14,"addition":0}},"items":[{"product":"Blink Home Security Camera  System 01","quantity":1,"detail":"Blink Home Security Camera  System 01","price":36600},{"product":"Australian Certified Organic Zucchini","quantity":1,"detail":"Product-007","price":58000}],"customer":{"taxDocument":{"type":"CPF","number":"31414212852"},"ownId":"suporte@skil.co.br","fullname":"testre er ","company":null,"phone":{"countryCode":55,"areaCode":63,"number":99287781},"email":"suporte@skil.co.br","birthDate":"1985-10-10","billingAddresses":{"zipCode":"77016-158","street":"ARSO 53 Alameda 6","streetNumber":"50","district":"Plano Diretor Sul","complement":"Plano Diretor Sul","city":"Palmas","state":"TO","country":"BRA"},"shippingAddress":{"zipCode":"77016-158","street":"ARSO 53 Alameda 6","streetNumber":"50","district":"Plano Diretor Sul","complement":"Plano Diretor Sul","city":"Palmas","state":"TO","country":"BRA"}},"device":{"ip":"172.16.0.17","userAgent":"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/87.0.4280.66 Safari\\/537.36"}}',
  'response' => '',
) [] []

![image](https://user-images.githubusercontent.com/74376574/102145630-533be880-3e46-11eb-9a06-b5b7e8d2f3be.png)

**Comment by elisei** [comment]
Oi @SuporteSkillsIT, tudo bem?

Nossa sandbox pode eventualmente apresentar indisponibilidade, não é muito comum mas eventualmente ocorre. Isso explica o item 2, quanto ao 1, você consegue me elaborar melhor cenário em que isso ocorre para eu possa reproduzi-lo em outros magentos?

**Comment by elisei** [comment]
Olá @SuporteSkillsIT 

Estou fechando o issue por falta de interação. Caso necessário por favor reabra! =)
