### ISSUE TITLE
Erro na compilação

### ISSUE THREAD

**Issue by samir-araujo** [wirecardBrasil/magento2#79]
Após instalar a extensão e rodar os comandos:

```
bin/magento setup:upgrade
bin/magento setup:di:compile
```

Ele dá o seguinte erro durante o processo do `bin/magento setup:di:compile`:

<img width="1161" alt="Screen Shot 2021-01-14 at 13 18 19" src="https://user-images.githubusercontent.com/5348274/104618056-00369a80-566b-11eb-83a5-c5d2e47faca1.png">

Alguém saberia me dizer como posso resolver este problema de compilação com está extensão, por favor?

**Comment by elisei** [comment]
Olá @samir-araujo 

Por favor, me informe:
 - Qual a versão da Magento
 - Qual a versão do módulo

**Comment by samir-araujo** [comment]
Olá, @elisei 

Segue:
Versão do Magento: 2.4 (Cloud)
Versão do módulo: ^2.0

**Comment by elisei** [comment]
Olá Samir,

Da magento a versão 2.4.0 ou 2.4.1. Eu preciso da versão exata por que não consigo reproduzir o erro no 2.4.1.
Sobre o nosso módulo por favor rode composer show moip/magento2

**Comment by samir-araujo** [comment]
@elisei ,

Acessando a rota `/magento_version` recebo o seguinte: Magento/2.3 (B2B)

Segue abaixo o print do `composer show` que pediu:

<img width="997" alt="Screen Shot 2021-01-14 at 15 28 10" src="https://user-images.githubusercontent.com/5348274/104633442-e6eb1980-567d-11eb-9f2b-73be94ea7a97.png">

**Comment by elisei** [comment]
Olá @samir-araujo 

Explicado =) Para magento 2.3 você pode seguir essa orientação!

<details>
<summary>
<i>Para Magento 2.3.x</i>
</summary>

```ssh
composer require moip/magento2:1.0.x
php bin/magento setup:upgrade
```

</details>

**Comment by samir-araujo** [comment]
Muito obrigado, @elisei !
