### ISSUE TITLE
Split de Pagamento

### ISSUE THREAD

**Issue by luizpuretz** [wirecardBrasil/magento2#80]
Olá,
já existe algo relacionado ao Split de pagamento dentro desse módulo, ou o split deve ficar apenas dentro das configurações do wirecard?

https://dev.wirecard.com.br/docs/split-de-pagamento

**Comment by elisei** [comment]
Olá @luizpuretz 

Não há, esse é um módulo destinado a e-commerce, para marketplace é ofertado diretamente pela empresa que desenvolve os recursos para essa funcionalidade na Magento, exemplo a Webkul "cria" o marketplace e oferta módulo para pagamento, seguindo os processos gerados por esse recurso, resultando assim em um módulo que irá consumir o recurso de split como pode [ver aqui](https://store.webkul.com/Magento2-Marketplace-Moip-Payment.html).
