### ISSUE TITLE
Erro na instalação

### ISSUE THREAD

**Issue by jguioliveira** [wirecardBrasil/magento2#81]
Magento 2.3.6
Moip 1.0.34

![image](https://user-images.githubusercontent.com/22643562/110633801-f3748580-8187-11eb-9737-85520175dd29.png)

**Comment by elisei** [comment]
Oi @jguioliveira 

Eu preciso de detalhes de como foi realizada a sua instalação, ao que parece algumas dependências não foram implementadas.

**Comment by jguioliveira** [comment]
Bom dia @elisei  

Instalação manual. Segui os passos da instalação manual (https://github.com/wirecardBrasil/magento2/wiki/Instala%C3%A7%C3%A3o#manual)

**Comment by elisei** [comment]
Oi @jguioliveira 

Para a instalação manual é necessário versões 2.4 em diante, para a sua versão atual é preciso fazer via composer:
https://github.com/wirecardBrasil/magento2/wiki/Instala%C3%A7%C3%A3o#instala%C3%A7%C3%A3o-via-composer

**Comment by jguioliveira** [comment]
Via composer funcionou, obrigado @elisei
