### ISSUE TITLE
Webhook - Status do pedido não é atualizado.

### ISSUE THREAD

**Issue by jguioliveira** [wirecardBrasil/magento2#82]
Bom dia!

Status do pedido não está sendo atualizado após confirmação de pagamento.
Testei no dois ambiente (sandbox e produção). A notificação consta como enviada no painel da Wirecard, porém o pedido não foi atualizado. 

SSL está ok.
Desconectei e conectei a conta novamente.

Magento 2.3.6
Moip 1.0.34

**Comment by elisei** [comment]
Olá @jguioliveira 

Temos uma documentação extensa sobre esse problema, [disponível aqui](https://github.com/wirecardBrasil/magento2/wiki/Atualiza%C3%A7%C3%A3o-de-Status#atualiza%C3%A7%C3%A3o-de-status).

Por favor, fique a vontade para reabrir o issue caso o problema persista.
