### ISSUE TITLE
Erro na compilação versão 2.3

### ISSUE THREAD

**Issue by guiserinoli** [wirecardBrasil/magento2#86]
Pessoal, após a instalação da versão 1.0 do módulo, está dando um erro relacionado ao moip-sdk-php:

PHP Fatal error:  Declaration of Moip\Auth\Connect::register(Requests_Hooks &$hooks) must be compatible with Requests_Auth::register(Requests_Hooks $hooks) in /mnt/BLOCKSTORAGE/home/591421.cloudwaysapps.com/dugazzunze/public_html/vendor/moip/moip-sdk-php/src/Auth/Connect.php on line 23

Poderiam checar, por favor? Como dito, a versão é a correta para o Magento 2.3.6, nunca houve erro nesse sentido nos nossos ambientes, apenas agora após uma atualização recente.

**Comment by elisei** [comment]
Olá @guiserinoli 

Desculpe a demora em responder.

Você efetuou a instalação do package pelo composer?

Vou deixar o issue fechado até que nos retorne, okay?

**Comment by guiserinoli** [comment]
Isso mesmo, pelo Composer. Instalei a versão 1 para o Magento 2.3, de acordo com o Wiki de vocês:
https://github.com/wirecardBrasil/magento2/wiki/Instala%C3%A7%C3%A3o#instala%C3%A7%C3%A3o-via-composer

Aparenta ser algo relacionado ao sdk que é requerido, algo que foi ajustado visando a versão para o Magento 2.4 porém, como na versão 1 do módulo de vocês não há o _required_ específico do sdk e sua versão, ocorreu o erro. Pelo menos é a impressão que tivemos.

**Comment by elisei** [comment]
Oi @guiserinoli 

Na verdade tanto a 2.3 como 2.4 não usam mais a SDK, ela é ainda requerida para a versão 2.2.x (deprecada oficialmente). Mas você testar de novo por favor, para isso corra:
composer require moip/magento2:1

**Comment by guiserinoli** [comment]
Excelente, Elisei! Obrigado!
Vejo que está em constante atualização também o módulo, vamos recomendar mais o Wirecard para nossos clientes, agradeço!
