### ISSUE TITLE
Problema na instalação via composer da versão mais recente para Magento 2.3.5-p1.

### ISSUE THREAD

**Issue by paulovictordev** [wirecardBrasil/magento2#87]
Olá, 

Gostaria de saber qual é a ultima versão compatível com a versão do Magento `2.3.5-p1`.

Tentei obter a versão do módulo `1.1.6`, mas obtive o seguinte erro:

Problem 1
    - Can only install one of: magento/framework[102.0.3, 102.0.5].
    - Can only install one of: magento/framework[102.0.3, 102.0.5].
    - Can only install one of: magento/framework[102.0.3, 102.0.5].
    - moip/magento2 1.1.6 requires magento/framework 102.0.3 -> satisfiable by magento/framework[102.0.3].
    - Installation request for moip/magento2 1.1.6 -> satisfiable by moip/magento2[1.1.6].
    - Installation request for magento/framework (locked at 102.0.5) -> satisfiable by magento/framework[102.0.5].
    
Isso é possivel ? 

Obrigado pelo desenvolvimento e manutenção do módulo.

**Comment by elisei** [comment]
Oi @paulovictordev tudo bem?

É compativel sim, mas cada versão maior da magento tem sua versão por aqui também. E nesse caso precisa rodar:

`composer require moip/magento2:1.1.6`

**Comment by paulovictordev** [comment]
@elisei obrigado pelo retorno rápido.

Rodei o comando, mas obtive a seguinte saida:

`Problem 1`
   ` - Installation request for moip/magento2 1.1.6 -> satisfiable by moip/magento2[1.1.6].`
    `- moip/magento2 1.1.6 requires magento/framework 102.0.3 -> no matching package found.`

**Comment by paulovictordev** [comment]
Percebi que a minha instalação do magento tem a versão `102.0.5` do módulo magento/framework.

e no require do moip solicita da versão `102.0.3` para o mesmo  "magento/framework": "102.0.3".

**Comment by elisei** [comment]
@paulovictordev exatamente.... subversões do m2.2.x.y.z.rs

Bom eu já subi uma correção da uns minutos e testa para mim por favor! <3

**Comment by paulovictordev** [comment]
@elisei, consegui fazer a instalação sem problemas!!!

Muito obrigado pelo feedback.
