### ISSUE TITLE
Cron cartão de crédito uma vez ao dia

### ISSUE THREAD

**Issue by cyberwork** [wirecardBrasil/magento2#88]
Olá utilizo o módulo e gostaria de saber pq o Cron que faz a mudança de status do pedido via Cartão de Crédito passou a rodar somente uma vez ao dia ao invés de ser a todo minuto,

Obrigado

**Comment by elisei** [comment]
Olá @cyberwork,

O Cron tem a finalidade de ser apenas para a consolidação de status em caso de uma falha de rede, indisponibilidade algum dos servidores envolvidos e qualquer outra "catástrofe"... 

O fluxo de entrega de status correto deve seguir apenas pelo [Webooks](https://github.com/wirecardBrasil/magento2/wiki/Atualiza%C3%A7%C3%A3o-de-Status#webhook). 

Havia ainda problema em gerar diversas informações no histórico do pedido quando o pedido se encontrava em uma análise manual por nosso time de risco (que poderia ficar até 48h nesse perfil) e gerava grande acumulo de informação na sua base de dados.
