### ISSUE TITLE
Configuração do Módulo desabilitada no admin

### ISSUE THREAD

**Issue by Samuel291** [wirecardBrasil/magento2#89]
Olá, bom dia!

Por algum motivo que desconheço o botão configurar da aba moip está desabilitado em meu painel admin, poderia me auxiliar como corrigir por gentileza?

Versão do Magento: 2.4.2
PS.: Este é o único usuário admin existente na instalação.
![image](https://user-images.githubusercontent.com/33501842/129166780-cf04398a-c6c4-42e9-8080-ac4f4d4c05e1.png)

**Comment by elisei** [comment]
Oi @Samuel291  tudo bem?

Eu vou precisar entre em contato no nosso email de suporte (magento@moip.com.br) pois vou precisar de alguns dados, nesse primeiro momento pelo o acesso admin.

Vou deixar o issue aberto até conseguirmos solucionar por lá. =)

**Comment by Samuel291** [comment]
Foi efetuada a instalação manual conforme orientação da wiki e o módulo funcionou perfeitamente
