### ISSUE TITLE
Erro: Classe não existente na versão do módulo moip/magento 1.1.10

### ISSUE THREAD

**Issue by paulovictordev** [wirecardBrasil/magento2#92]
Olá, hoje eu tentei atualizar umas de nossas lojas e o composer update obteve a ultimas versão do modulo para a minha versão do Magento 2.3.5.

Ao rodar o seguinte o comando `bin/magento setup:upgrade`, após a atualização do composer recebi o seguinte erro:

`Class Moip\Magento2\Console\Command\Preference\CreateWebhook\Interceptor does not exist`  

Percebi que essa classe usa os recursos do Model Create `Moip\Magento2\Model\Console\Command\Preference\Create`, que não existe nessa versão `moip/magento 1.1.10`.

**Comment by elisei** [comment]
@paulovictordev 

Você tem razão, pedimos desculpa pela falha, realmente faltou enviar a pasta na versão 2.3.x o.O corrigido já na tag 1.1.11
