### ISSUE TITLE
Magento 2.4.4 (erro?)

### ISSUE THREAD

**Issue by schossler** [wirecardBrasil/magento2#99]
Não tive sucesso em fazer o módulo funcionar no Magento 2.4.4. Não gerou erro no log, mas ao selecionar  boleto ou cartão não carregou as opções para finalizar a compra.

**Comment by elisei** [comment]
Olá Schossler,

Você fez a instalação via composer?

Eu lancei ontem a versão compatível, ela está disponível aqui:
https://github.com/elisei/moip-payment-magento2 mas recomendo que a
instalação seja via composer!

Isto fica feliz em ser útil.


*Bruno Elisei*
*O2**ti Soluções Web*
(34) 98442-7885



Em qua., 27 de abr. de 2022 às 00:04, schossler ***@***.***>
escreveu:

**Comment by schossler** [comment]
Sim via composer, obrigado Bruno.

**Comment by schossler** [comment]
Bruno consegue passar instruções de como altero meu composer.json para usar seu repo ?

**Comment by elisei** [comment]
Olá Shossler,

Você não precisa alterar o seu composer, no máximo tente fazer:
composer remove moip/magento2
e depois:
composer require moip/magento2

Mas há outros passos que podem ser mais úteis:
- Se tiver usando algum tema, configure para usar o tema "luma"
- Se tiver usando algum módulo de checkout (que não o nativo) tente
desabilitado


Isto fica feliz em ser útil.


*Bruno Elisei*
*O2**ti Soluções Web*
(34) 98442-7885



Em qui., 28 de abr. de 2022 às 09:15, schossler ***@***.***>
escreveu:
